import { Product, Category } from "@/types";

export const demoCategories: Category[] = [
  { id: "1", name: "Websites", slug: "websites", icon: "Globe", count: 156 },
  { id: "2", name: "Landing Pages", slug: "landing-pages", icon: "Layout", count: 243 },
  { id: "3", name: "Dashboards", slug: "dashboards", icon: "LayoutDashboard", count: 89 },
  { id: "4", name: "Templates", slug: "templates", icon: "FileCode", count: 312 },
  { id: "5", name: "Scripts", slug: "scripts", icon: "Code", count: 178 },
  { id: "6", name: "HTML5 Games", slug: "html5-games", icon: "Gamepad2", count: 67 },
  { id: "7", name: "UI Kits", slug: "ui-kits", icon: "Palette", count: 134 },
  { id: "8", name: "Web Tools", slug: "web-tools", icon: "Wrench", count: 95 },
];

export const demoProducts: Product[] = [
  {
    id: "1",
    title: "Quantum Dashboard Pro",
    slug: "quantum-dashboard-pro",
    description:
      "A stunning admin dashboard template built with React and Tailwind CSS. Features real-time analytics, advanced charts, dark mode, and 50+ pre-built components.",
    features: [
      "React 18 + TypeScript",
      "50+ Components",
      "Dark & Light Mode",
      "Real-time Analytics",
      "Responsive Design",
      "Chart.js Integration",
    ],
    price: 49,
    old_price: 79,
    category: "dashboards",
    tags: ["react", "dashboard", "admin", "analytics"],
    thumbnail:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop",
    ],
    preview_video: null,
    demo_url: "https://example.com/demo",
    zip_file: null,
    sales: 1247,
    views: 15680,
    rating: 4.8,
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "2",
    title: "Nova Landing Page Kit",
    slug: "nova-landing-page-kit",
    description:
      "12 beautiful landing page templates for SaaS products, startups, and agencies. Fully responsive with smooth animations.",
    features: [
      "12 Unique Designs",
      "Framer Motion Animations",
      "SEO Optimized",
      "Contact Form Ready",
      "Newsletter Integration",
      "Mobile First",
    ],
    price: 39,
    old_price: 59,
    category: "landing-pages",
    tags: ["landing-page", "saas", "startup", "responsive"],
    thumbnail:
      "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&h=600&fit=crop",
    ],
    preview_video: null,
    demo_url: "https://example.com/demo",
    zip_file: null,
    sales: 892,
    views: 12340,
    rating: 4.9,
    created_at: "2026-02-20T00:00:00Z",
  },
  {
    id: "3",
    title: "Pixel Quest - HTML5 Game",
    slug: "pixel-quest-html5-game",
    description:
      "An engaging pixel-art platformer game built with Phaser.js. Includes 20 levels, power-ups, leaderboard, and mobile touch controls.",
    features: [
      "20 Unique Levels",
      "Mobile Touch Controls",
      "Leaderboard System",
      "Power-ups & Collectibles",
      "Sound Effects & Music",
      "Save Progress",
    ],
    price: 29,
    old_price: null,
    category: "html5-games",
    tags: ["game", "html5", "phaser", "pixel-art"],
    thumbnail:
      "https://images.unsplash.com/photo-1556438064-2d7646166914?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1556438064-2d7646166914?w=800&h=600&fit=crop",
    ],
    preview_video: null,
    demo_url: "https://example.com/demo",
    zip_file: null,
    sales: 456,
    views: 8920,
    rating: 4.6,
    created_at: "2026-03-10T00:00:00Z",
  },
  {
    id: "4",
    title: "Starter UI Kit",
    slug: "starter-ui-kit",
    description:
      "A comprehensive UI kit with 200+ components designed in Figma with coded React components. Perfect for rapid prototyping.",
    features: [
      "200+ Components",
      "Figma Source Files",
      "React Components",
      "Design Tokens",
      "Accessibility Ready",
      "Documentation",
    ],
    price: 69,
    old_price: 99,
    category: "ui-kits",
    tags: ["ui-kit", "figma", "react", "components"],
    thumbnail:
      "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=600&fit=crop",
    ],
    preview_video: null,
    demo_url: "https://example.com/demo",
    zip_file: null,
    sales: 723,
    views: 10450,
    rating: 4.7,
    created_at: "2026-01-28T00:00:00Z",
  },
  {
    id: "5",
    title: "E-Commerce Pro Template",
    slug: "e-commerce-pro-template",
    description:
      "Full-featured e-commerce website template with product management, cart, checkout, and payment integration. Built with Next.js.",
    features: [
      "Next.js 14",
      "Shopping Cart",
      "Stripe Integration",
      "Product Management",
      "Order Tracking",
      "SEO Optimized",
    ],
    price: 89,
    old_price: 129,
    category: "websites",
    tags: ["ecommerce", "nextjs", "stripe", "shopping"],
    thumbnail:
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&h=600&fit=crop",
    ],
    preview_video: null,
    demo_url: "https://example.com/demo",
    zip_file: null,
    sales: 1567,
    views: 22340,
    rating: 4.9,
    created_at: "2026-04-05T00:00:00Z",
  },
  {
    id: "6",
    title: "AutoBot Scripts Bundle",
    slug: "autobot-scripts-bundle",
    description:
      "A collection of 15 powerful automation scripts for web scraping, data processing, and API integration. Python & Node.js.",
    features: [
      "15 Scripts",
      "Python & Node.js",
      "API Integration",
      "Data Processing",
      "Documentation",
      "Lifetime Updates",
    ],
    price: 35,
    old_price: 55,
    category: "scripts",
    tags: ["scripts", "automation", "python", "nodejs"],
    thumbnail:
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=600&fit=crop",
    ],
    preview_video: null,
    demo_url: null,
    zip_file: null,
    sales: 334,
    views: 6780,
    rating: 4.5,
    created_at: "2026-03-22T00:00:00Z",
  },
  {
    id: "7",
    title: "Portfolio Starter Template",
    slug: "portfolio-starter-template",
    description:
      "A minimal and elegant portfolio template for designers and developers. Features smooth page transitions and CMS integration.",
    features: [
      "Minimal Design",
      "Page Transitions",
      "CMS Ready",
      "Blog Section",
      "Contact Form",
      "Fast Loading",
    ],
    price: 25,
    old_price: null,
    category: "templates",
    tags: ["portfolio", "minimal", "developer", "designer"],
    thumbnail:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop",
    ],
    preview_video: null,
    demo_url: "https://example.com/demo",
    zip_file: null,
    sales: 567,
    views: 9870,
    rating: 4.4,
    created_at: "2026-04-12T00:00:00Z",
  },
  {
    id: "8",
    title: "DevTools Suite",
    slug: "devtools-suite",
    description:
      "Essential web development tools including CSS generators, color pickers, code formatters, and performance analyzers.",
    features: [
      "CSS Generators",
      "Color Palette Tools",
      "Code Formatter",
      "Performance Analyzer",
      "SEO Checker",
      "API Tester",
    ],
    price: 45,
    old_price: 65,
    category: "web-tools",
    tags: ["tools", "developer", "css", "performance"],
    thumbnail:
      "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=600&fit=crop",
    ],
    preview_video: null,
    demo_url: "https://example.com/demo",
    zip_file: null,
    sales: 289,
    views: 5430,
    rating: 4.3,
    created_at: "2026-02-14T00:00:00Z",
  },
];

export const demoTestimonials = [
  {
    id: "1",
    name: "Sarah Chen",
    role: "Full Stack Developer",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    comment:
      "Nexora's templates saved me weeks of development time. The code quality is exceptional and the designs are stunning.",
    rating: 5,
  },
  {
    id: "2",
    name: "Ahmed Hassan",
    role: "UI/UX Designer",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    comment:
      "The UI kits are incredibly well-designed. Every component is pixel-perfect and easy to customize.",
    rating: 5,
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    role: "Startup Founder",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    comment:
      "We launched our SaaS product in half the time thanks to Nexora's dashboard templates. Highly recommended!",
    rating: 5,
  },
  {
    id: "4",
    name: "James Liu",
    role: "Frontend Engineer",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    comment:
      "Outstanding quality and support. The scripts bundle automated our entire deployment pipeline.",
    rating: 4,
  },
];
